### ISSUE TITLE
intersections.

### ISSUE THREAD

**Issue by mo-c** [mo-c/moses-cpp-learning#41]
how do i do the conditions for the two lines.

**Comment by lcabrini** [comment]
First of all, you *can* have more than one label. This is an excersise issue, so it should still have the exercise label. You also need help with it, so you add the 'help wanted' label. Utilize labels to your benefit.

**Comment by lcabrini** [comment]
Here is an introduction to the topic:
https://en.wikipedia.org/wiki/Line-line_intersection

You have to get used to researching. Just like the straight-line program, you ask the user to enter coordinates for the two lines. Then you calculate the gradient and the intercept. Using those, you can find the point of intersection, in such cases where one exists.

You need to make an attempt at researching and trying to tie the topic back to your C++ code. That is a primary skill that you must have.

**Comment by mo-c** [comment]
I have done that already my problem is the condition where I have to use
the two lines

**Comment by lcabrini** [comment]
Ah, do you mean the conditions for when the two lines actually do intersect? In that case, you have three possibilities:

1. The lines are parallel: that is true if the slopes are the same, but the point of intersection is not. In this case you cannot find the point of intersection
2. The lines are identical. This is true if both the gradient and the intercept are the same. In this case the point of intersection doesn't make sense because they intersect on all points
3. In all other cases, there should be a point of intersection

So you first check if both m1 == m2 and b1 == b2. In that case, the lines are identical
Then you check if m1 == m2. if so, the lines are parallel
Otherwise, you calculate the point of interceptions
